# Generated by Django 4.2.7 on 2023-11-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ingredientsmodel_menuitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='special_status',
            field=models.CharField(blank=True, default='No', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SpecialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='menu.menuitems')),
            ],
        ),
    ]
