# Generated by Django 4.2.7 on 2023-11-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitems_special_status_specialsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='menu.menuitems')),
            ],
        ),
        migrations.CreateModel(
            name='TableOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(blank=True, max_length=200, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('orders', models.ManyToManyField(blank=True, default=None, related_name='orders', to='menu.ordermodel')),
            ],
        ),
        migrations.CreateModel(
            name='RemovedIngredientsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('ingredients', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_ingredient', to='menu.ingredientsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='removed_ingredient',
            field=models.ManyToManyField(blank=True, default=None, related_name='removed_ingredients', to='menu.removedingredientsmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='speacial',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_order', to='menu.specialsmodel'),
        ),
    ]
