# Generated by Django 4.2.7 on 2023-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_ordermodel_tableordermodel_removedingredientsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='currentUser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='table',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
